[package]
name = "mlfq-panic"
version = "0.1.0"
edition = "2024"

[package.metadata.flux]
enabled = true

[dependencies]
flux-rs = { git = "https://github.com/flux-rs/flux.git" }
flux-assume = { path = "../flux-assume" }
rand = "0.9.0"
